name: Build & Test

on: pull_request

jobs:
  build_and_test:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore
        run: |
          dotnet restore
      - name: Build
        run: |
          dotnet build --no-restore
      - name: Test
        run: |
          dotnet test --no-build